### ISSUE TITLE
error

### ISSUE THREAD

**Issue by andrevitxr** [Sattishh/voice-interrupter-discord-bot#3]
C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\util\loader.js:12
  throw new Error(errorLog.join('\n'));
        ^

Error: Error: Cannot find module '@discordjs/opus'
Require stack:
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\util\loader.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\opus\Opus.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\opus\index.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\index.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\Client.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\index.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\index.js
Error: Cannot find module 'node-opus'
Require stack:
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\util\loader.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\opus\Opus.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\opus\index.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\index.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\Client.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\index.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\index.js
Error: Cannot find module 'opusscript'
Require stack:
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\util\loader.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\opus\Opus.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\opus\index.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\index.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\Client.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\index.js
- C:\xampp\htdocs\voice-interrupter-discord-bot-main\index.js
    at Object.loader [as require] (C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\util\loader.js:12:9)
    at loadOpus (C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\opus\Opus.js:17:17)
    at new OpusStream (C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\opus\Opus.js:46:10)
    at new Encoder (C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\prism-media\src\opus\Opus.js:149:5)
    at AudioPlayer.playPCMStream (C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\player\BasePlayer.js:58:34)
    at AudioPlayer.playUnknown (C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\player\BasePlayer.js:53:17)
    at VoiceConnection.play (C:\xampp\htdocs\voice-interrupter-discord-bot-main\node_modules\discord.js\src\client\voice\util\PlayInterface.js:71:28)
    at C:\xampp\htdocs\voice-interrupter-discord-bot-main\index.js:42:24

**Comment by Sattishh** [comment]
Hey @playboyander, please do the following commands in your cli in the bot folder
`npm i @discordjs/opus node-opus opusscript`

The general idea is that if the node error is *Cannot find module 'something'* you should do `npm i something`

Please let me know whether this fixed the issue or not!

**Comment by andrevitxr** [comment]
package.lock is old, it was created on an older version of npm, it doesn't support discord.js@12.5.3

you need to update package.lock

**Comment by Sattishh** [comment]
Do `npm rebuild`
